#############################################################################
# Makefile for building: MatrizCoocorrenciaOpenMP
# Generated by qmake (2.01a) (Qt 4.8.6) on: qui fev 25 14:11:30 2016
# Project:  MatrizCoocorrenciaOpenMP.pro
# Template: app
# Command: /opt/Trolltech/Qt-4.8.6/bin/qmake -spec /opt/Trolltech/Qt-4.8.6/mkspecs/linux-g++ -o Makefile MatrizCoocorrenciaOpenMP.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -O2 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -openmp -O3 -Wall -W $(DEFINES)
INCPATH       = -I/opt/Trolltech/Qt-4.8.6/mkspecs/linux-g++ -I.
LINK          = g++
LFLAGS        = -openmp -O3 -Wl,-rpath,/opt/Trolltech/Qt-4.8.6/lib
LIBS          = $(SUBLIBS)    
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/Trolltech/Qt-4.8.6/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = Obj/

####### Files

SOURCES       = main.cpp \
		gerarmatriz.cpp \
		hex2int.cxx \
		readimage.cpp \
		haralick.cpp 
OBJECTS       = Obj/main.o \
		Obj/gerarmatriz.o \
		Obj/hex2int.o \
		Obj/readimage.o \
		Obj/haralick.o
DIST          = /opt/Trolltech/Qt-4.8.6/mkspecs/common/unix.conf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/common/linux.conf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/common/gcc-base.conf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/common/gcc-base-unix.conf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/common/g++-base.conf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/common/g++-unix.conf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/qconfig.pri \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/qt_functions.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/qt_config.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/exclusive_builds.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/default_pre.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/release.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/default_post.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/static.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/warn_on.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/resources.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/uic.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/yacc.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/lex.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/include_source_dir.prf \
		MatrizCoocorrenciaOpenMP.pro
QMAKE_TARGET  = MatrizCoocorrenciaOpenMP
DESTDIR       = 
TARGET        = MatrizCoocorrenciaOpenMP

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MatrizCoocorrenciaOpenMP.pro  /opt/Trolltech/Qt-4.8.6/mkspecs/linux-g++/qmake.conf /opt/Trolltech/Qt-4.8.6/mkspecs/common/unix.conf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/common/linux.conf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/common/gcc-base.conf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/common/gcc-base-unix.conf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/common/g++-base.conf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/common/g++-unix.conf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/qconfig.pri \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/qt_functions.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/qt_config.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/exclusive_builds.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/default_pre.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/release.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/default_post.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/static.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/warn_on.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/resources.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/uic.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/yacc.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/lex.prf \
		/opt/Trolltech/Qt-4.8.6/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /opt/Trolltech/Qt-4.8.6/mkspecs/linux-g++ -o Makefile MatrizCoocorrenciaOpenMP.pro
/opt/Trolltech/Qt-4.8.6/mkspecs/common/unix.conf:
/opt/Trolltech/Qt-4.8.6/mkspecs/common/linux.conf:
/opt/Trolltech/Qt-4.8.6/mkspecs/common/gcc-base.conf:
/opt/Trolltech/Qt-4.8.6/mkspecs/common/gcc-base-unix.conf:
/opt/Trolltech/Qt-4.8.6/mkspecs/common/g++-base.conf:
/opt/Trolltech/Qt-4.8.6/mkspecs/common/g++-unix.conf:
/opt/Trolltech/Qt-4.8.6/mkspecs/qconfig.pri:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/qt_functions.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/qt_config.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/exclusive_builds.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/default_pre.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/release.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/default_post.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/static.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/unix/gdb_dwarf_index.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/warn_on.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/resources.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/uic.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/yacc.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/lex.prf:
/opt/Trolltech/Qt-4.8.6/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /opt/Trolltech/Qt-4.8.6/mkspecs/linux-g++ -o Makefile MatrizCoocorrenciaOpenMP.pro

dist: 
	@$(CHK_DIR_EXISTS) Obj/MatrizCoocorrenciaOpenMP1.0.0 || $(MKDIR) Obj/MatrizCoocorrenciaOpenMP1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) Obj/MatrizCoocorrenciaOpenMP1.0.0/ && (cd `dirname Obj/MatrizCoocorrenciaOpenMP1.0.0` && $(TAR) MatrizCoocorrenciaOpenMP1.0.0.tar MatrizCoocorrenciaOpenMP1.0.0 && $(COMPRESS) MatrizCoocorrenciaOpenMP1.0.0.tar) && $(MOVE) `dirname Obj/MatrizCoocorrenciaOpenMP1.0.0`/MatrizCoocorrenciaOpenMP1.0.0.tar.gz . && $(DEL_FILE) -r Obj/MatrizCoocorrenciaOpenMP1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

Obj/main.o: main.cpp readimage.h \
		globalvar.h \
		haralick.h \
		tempo.h \
		utilidades.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Obj/main.o main.cpp

Obj/gerarmatriz.o: gerarmatriz.cpp gerarmatriz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Obj/gerarmatriz.o gerarmatriz.cpp

Obj/hex2int.o: hex2int.cxx hex2int.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Obj/hex2int.o hex2int.cxx

Obj/readimage.o: readimage.cpp readimage.h \
		globalvar.h \
		hex2int.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Obj/readimage.o readimage.cpp

Obj/haralick.o: haralick.cpp haralick.h \
		globalvar.h \
		tempo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Obj/haralick.o haralick.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

